###################
# {{ ansible_managed }} #
###################

version: '3'

services:
  sonarqube:
    image: sonarqube:alpine
    container_name: metio-sonarqube
    volumes:
      - /var/opt/sonarqube/extensions:/opt/sonarqube/extensions
      - /var/opt/sonarqube/data:/opt/sonarqube/data
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres/sonar
    links:
      - postgres
    ports:
      - "{{ sonarqube_port }}:9000"
  postgres:
    image: postgres:alpine
    container_name: metio-sonarqube-psql
    environment:
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_USER=sonar
    volumes:
      - /var/opt/sonarqube/psql:/var/lib/postgresql/data
    expose:
      - "5432"
